// AUTO-GENERATED by scripts/sync-games.mjs — do not edit manually
// Add games by creating games/<name>/plugin.ts and re-running `npm run games:sync`
import type { GamePlugin } from "./types";
import { plugin as plugin_guess_the_number } from "../../games/guess-the-number/plugin";
import { plugin as plugin_pool_dooks } from "../../games/pool-dooks/plugin";

const registry = new Map<string, GamePlugin>([
  [plugin_guess_the_number.gameType, plugin_guess_the_number],
  [plugin_pool_dooks.gameType, plugin_pool_dooks],
]);

export function getPlugin(gameType: string): GamePlugin {
  const plugin = registry.get(gameType);
  if (!plugin) throw new Error(`Unknown game type: ${gameType}`);
  return plugin;
}

export function listPlugins(): GamePlugin[] {
  return Array.from(registry.values());
}
