#!/usr/bin/env node
// Auto-generates lib/games/registry.ts by scanning games/*/plugin.ts.
// Run via `npm run games:sync` or automatically as prebuild/predev.
import { readdirSync, existsSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const gamesDir = join(root, "games");
const outFile = join(root, "lib", "games", "registry.ts");

const gameDirs = readdirSync(gamesDir, { withFileTypes: true })
  .filter((d) => d.isDirectory() && existsSync(join(gamesDir, d.name, "plugin.ts")))
  .map((d) => d.name);

if (gameDirs.length === 0) {
  console.warn("No games found in games/ directory.");
}

const imports = gameDirs
  .map((d) => `import { plugin as plugin_${toVarName(d)} } from "../../games/${d}/plugin";`)
  .join("\n");

const entries = gameDirs
  .map((d) => `  [plugin_${toVarName(d)}.gameType, plugin_${toVarName(d)}]`)
  .join(",\n");

const content = `// AUTO-GENERATED by scripts/sync-games.mjs — do not edit manually
// Add games by creating games/<name>/plugin.ts and re-running \`npm run games:sync\`
import type { GamePlugin } from "./types";
${imports}

const registry = new Map<string, GamePlugin>([
${entries},
]);

export function getPlugin(gameType: string): GamePlugin {
  const plugin = registry.get(gameType);
  if (!plugin) throw new Error(\`Unknown game type: \${gameType}\`);
  return plugin;
}

export function listPlugins(): GamePlugin[] {
  return Array.from(registry.values());
}
`;

writeFileSync(outFile, content, "utf-8");
console.log(`Generated registry with ${gameDirs.length} game(s): ${gameDirs.join(", ")}`);

function toVarName(dir) {
  return dir.replace(/-/g, "_");
}
